application: novidadeshtml5-devfest
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images/chrome-logo-tiny\.png
  static_files: images/chrome-logo-tiny.png
  upload: images/chrome-logo-tiny\.png

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /demos
  static_dir: demos

- url: /shaders
  static_dir: shaders

- url: /theme
  static_dir: theme

- url: /slide_config.js
  static_files: slide_config.js
  upload: slide_config.js

- url: /
  static_files: index.html
  upload: index.html

#- url: .*
#  script: main.app

# libraries:
# - name: webapp2
#   version: "2.5.1"
